# docker-compose.yml
version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    ports:
      - "27021:27017"